name: Update AtomVids Data
on:
  repository_dispatch:
    types: [update_likes, new_user]

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update JSON
        run: |
          VIDEO_ID="${{ github.event.client_payload.video_id }}"
          # This command creates the video ID if it's missing and adds 1 like
          jq --arg id "$VIDEO_ID" '.[$id].likes = (.[$id].likes // 0) + 1' stats.json > tmp.json && mv tmp.json stats.json

      - name: Commit and Push
        run: |
          git config --global user.name "AtomVids-Bot"
          git config --global user.email "bot@atomvids.com"
          git add stats.json
          git commit -m "Update Likes for $VIDEO_ID"
          git push
